#cloud-config
package_upgrade: true
packages:
  - nvme-cli
bootcmd:
  - test -z "$(blkid {$ebs_device_name})" && mkfs -t ext4 -L factorio ${ebs_device_name}
mounts:
  - [ "${ebs_device_name}", "/mnt/factorio", "ext4", "defaults,nofail", "0", "2" ]
runcmd:
  - adduser --disabled-login --gecos GECOS --no-create-home --home /opt/factorio factorio
  - mkdir -p /mnt/factorio/saves
  - curl -L "https://www.factorio.com/get-download/${factorio_version}/headless/linux64" -o /opt/factorio.tar.gz
  - su factorio
  - cd /opt
  - tar xvf factorio.tar.gz
  - chown factorio. -R /opt/factorio
  - ln -s /mnt/factorio/saves /opt/factorio/saves
