#cloud-config
repo_update: true
repo_upgrade: security
package_upgrade: true
packages:
  - nvme-cli
  - awscli
bootcmd:
  - test -z "$(blkid {$ebs_device_name})" && mkfs -t ext4 -L factorio ${ebs_device_name}
mounts:
  - [ "${ebs_device_name}", "/mnt/factorio", "ext4", "defaults,nofail", "0", "2" ]
runcmd:
  - set -e
  - adduser --disabled-login --gecos GECOS --no-create-home --home /opt/factorio factorio
  - curl -L "https://www.factorio.com/get-download/${factorio_version}/headless/linux64" -o /opt/factorio.tar.gz
  - tar -C /opt -x -f /opt/factorio.tar.gz
  - mkdir -p /opt/factorio/saves
  - chown factorio. -R /opt/factorio
